# site
exclude:        [CNAME, README.md, .gitignore]
permalink:      /
timezone:       null
lsi:            false
markdown:       kramdown
highlighter:    pygments

# content
title:          Lensed
description: >
    Reconstruct gravitational lenses and lensed sources from
    strong lensing observations.
source_link:    https://github.com/glenco/lensed
keywords: >
  lensed, lensing, gravitational lensing, reconstruction, fits, mcmc,
  observations, models, astronomy
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: 

# colors
colors:
  black:    '#000000'
  white:    '#ffffff'
  yellow:   '#b58900'
  orange:   '#cb4b16'
  red:      '#dc322f'
  magenta:  '#d33682'
  violet:   '#6c71c4'
  blue:     '#268bd2'
  cyan:     '#2aa198'
  green:    '#859900'
